# Generated by Django 6.0.4 on 2026-05-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'paye'), ('expire', 'expire')], default='en_attente')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
        ),
    ]
