# Generated by Django 6.0.4 on 2026-05-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
