# Generated by Django 6.0.4 on 2026-05-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('aesm', '0002_delete_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'paye'), ('expire', 'expire')], default='en_attente')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_payement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Echec')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='aesm.inscription')),
            ],
        ),
    ]
