# Generated by Django 6.0.4 on 2026-05-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='quitus/')),
                ('fichier_pdf', models.FileField(upload_to='quitus/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aesm.paiement')),
            ],
        ),
    ]
