# Generated by Django 6.0.4 on 2026-05-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0004_quitus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quitus',
            name='paiement',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Quitus',
        ),
    ]
