# Generated by Django 6.0.4 on 2026-05-04 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0005_remove_quitus_paiement_delete_paiement_delete_quitus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_payement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Echec')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='aesm.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='quitus/')),
                ('fichier_pdf', models.FileField(upload_to='quitus/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aesm.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('montant', models.IntegerField()),
                ('description', models.TextField()),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='aesm.rapport')),
            ],
        ),
    ]
