# Generated by Django 6.0.4 on 2026-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0006_paiement_quitus_rapport_lignebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
    ]
