# Generated by Django 6.0.4 on 2026-05-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesm', '0007_paiement_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='admin',
        ),
        migrations.DeleteModel(
            name='LigneBudget',
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
