# Generated by Django 6.0.4 on 2026-05-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
