# Generated by Django 6.0.4 on 2026-05-06 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_publication_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('AESM', 'AESM'), ('CR', 'Centre de Réflexion')], max_length=10)),
                ('fichier', models.FileField(upload_to='fichiers/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('access', models.CharField(choices=[('AESM', 'AESM'), ('CR', 'Centre de Réflexion')], default='public')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cr.filecategory')),
            ],
        ),
    ]
