# Generated by Django 6.0.4 on 2026-05-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0003_filecategory_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
