# Generated by Django 6.0.4 on 2026-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='contenu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
