# Generated by Django 6.0.4 on 2026-05-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_files_contenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
