# Generated by Django 6.0.4 on 2026-05-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0011_publication_like_count_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='count_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
