# Generated by Django 6.0.4 on 2026-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0012_publication_count_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('AESM', 'AESM'), ('CR', 'Centre de Réflexion')], default='AESM', max_length=10),
            preserve_default=False,
        ),
    ]
