# Generated by Django 6.0.4 on 2026-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0013_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='section',
            field=models.CharField(choices=[('AESM', 'AESM'), ('CR', 'Centre de Réflexion')], default='AESM', max_length=10),
            preserve_default=False,
        ),
    ]
